language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"

deploy:
  provider: npm
  email: takuma.kamigaoka@gmail.com
  on:
    tags: true
  api_key:
    secure: r+rFa3eUDLLPp9JHAcaauCi2rBOo2JBrHQu3KcJnGF8vMW5MX9yVEILn0W7/0zgwe0dEnHyeFKYvrUZit4i7CE0exjf4WRjE4z81BipNxRkBT4zJZNRni1Xl/qWzi00aZflG4jdEsijf5Xlc114L3chFbB86KBvj/J0Kf0JkA/OdsH1NjHD8+b0S8hBpCxVXMpglNHUrNcLjRuG8BpppTO0ShFZy+Acrh2CHlks88kdBBkltcIDds3IqO2KWi9QYYIctot0bwV8wOZmRV0CV/MugxkG597x97oB1n6x8LpWKSuRxp3h0ESaOd87YuPFSv/C0C7itwzXCSkqR46mV/CerwwZsnbPudJdifxXt+cchUjQfSziRtQwI34Elxxv63GyD82obH8Cn/kGMAfFQoEuA5vCNzPxF4+5V5aKRTtUDgPFYqwJsRI3cezFqfCl7+PDLUinRPkFoXtU1eRa1z3kK+UvkelH08Dfhlz0Sa9c3VSYujI7ZPApyUHqhb/VppyFkqzo7geoEwHnWiQbLhWo07thMoFMZ7uMcvVmUrjsVVAfRdtugcJF0RufJ9ngw3zhEe1eAHyZoqK28idtk7Hrkilje3XXL8DAsjRZAbylW5fc0qEN8OHHgxLAsJb3m7XQWiEugaV07r7trSr4+ZQ0aPr8pvSgG1BJ4X+7OF6U=
